package org.sample.c.checks;

import java.io.File;
import java.util.Set;

import org.apache.commons.io.FileUtils;
import org.junit.Test;
import org.sonar.squid.api.CheckMessage;

import com.sonar.c.CAstScanner;
import com.sonar.sslr.squid.checks.CheckMessagesVerifier;

public class GotoStatementCheckTest {

  @Test
  public void shouldGetOneViolation() {
    // 1- Get an handle on the C source file which must be analyzed
    File cSourceFile = FileUtils.toFile(GotoStatementCheckTest.class.getResource("/checks/goto_statement.c"));

    // 2- Analyze this source file with the GotoStatementCheck and retrieve the list of all check messages generated by this check
    Set<CheckMessage> violations = CAstScanner.scanSingleFile(cSourceFile, new GotoStatementCheck()).getCheckMessages();

    // 3- Test those violations to be sure that we get the expected result
    CheckMessagesVerifier.verify(violations).next().atLine(13).withMessage("Avoid using goto statement.").noMore();
  }
}
